### ISSUE TITLE
Site 124 - Webster City - Billing Issues

### ISSUE THREAD

**Issue by kdjstudios** [kdjstudios/SABillingGitlab#571]
In GitLab by @kdjstudios on Nov 20, 2017, 15:14

**Submitted by:** "Jesus Corchado" <jesus.corchado@answernet.com>

**Helpdesk:** http://www.servicedesk.answernet.com/profiles/ticket/2017-11-20-52966/conversation

**Server:** Internal

**Client/Site:** Webster City

**Account:** NA

**Issue:** 

I received this while trying to upload a DFT file.
 
![image001](/uploads/b1bcf9a477f7f19751a596f021becbe6/image001.jpg)
In addition, the account is not grasping the codes created and needed to process billing for the account; Farm Journal Media.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 20, 2017, 15:16

@smasih @tim.traylor 

It looks like there was never a posting script added?

It looks like the site went in and added the additional fees, but did not add the activities. Should we also add the activites in for them?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Nov 21, 2017, 02:43

@kdjstudios 

* Go to https://answernet.sabilling.com/admin/cdr_ftp_host/edit (admin access required)
* Select site and create the cdr directory. **Give Site number under Directory column on this page.**
* ![Screenshot-1](/uploads/b121e06412fc2b214dbd8ec23fbd5c9e/Screenshot-1.png)
* **Then we have to copy the posting script in /home/sabilling/posting_scripts.** So, just send us the Posting script either [Tim](@tim.traylor) or we can do it.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 21, 2017, 07:57

@smasih 

Thanks, I will add that to the directions on setting up a new site. I will post an update if @tim.traylor is unable to upload the posting script.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 21, 2017, 09:45

Closing ticket, Tim was able to upload the posting script.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 28, 2017, 08:56

Reopening ticket:

Response from Jesus -

I tried uploading the DFT file but I keep getting the error page.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 28, 2017, 08:56

reopened

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 28, 2017, 08:57

@tim.traylor @smasih 

May we please look into why Jesus is receiving the error page and resolve this.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 28, 2017, 12:29

@tim.traylor was able to find this error:

> A StandardError occurred in billing_cycles#upload:
> 
>   Cannot convert the raw file.
> [/home/sabilling/posting_scripts/124.sh /home/sabilling/localftp/124/SAB_empty_usage.txt.20171128141129 /home/sabilling/localftp/124/SAB_empty_usage.txt.20171128141129.20171128141129]
>   app/services/cdr_importer.rb:121:in `run_posting_script'

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Nov 28, 2017, 23:45

@tim.traylor @kdjstudios 

The posting script for **124 - Webster City** was an executable file `124.sh` without permission to execute. So we just updated the permission and it's working now.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Nov 28, 2017, 23:45

added 30m of time spent at 2017-11-29

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Nov 28, 2017, 23:47

added 1h of time spent at 2017-11-29

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 29, 2017, 24:31

@smasih @tim.traylor 

Tried to upload this blank usage file: [Webster_City_empty_usage.txt](/uploads/78b39a255423121772b985084429b7fa/Webster_City_empty_usage.txt)

Was presented with the "Something went wrong" error. Also the following error was sent via email:

A StandardError occurred in billing_cycles#upload:

  Cannot convert the raw file.
[/home/sabilling/posting_scripts/124.sh /home/sabilling/localftp/124/Webster City_empty_usage.txt.20171129022153 /home/sabilling/localftp/124/Webster City_empty_usage.txt.20171129022153.20171129022153]
  app/services/cdr_importer.rb:121:in `run_posting_script'

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Nov 29, 2017, 24:45

@kdjstudios 

rename the file like [webster5.txt](/uploads/f61641e20ef51f803c40dd0fc3683328/webster4.txt) or **webster_City_empty_usage.txt** in short first letter of the file shouldn't be capital.

File name should be without spaces and first letter shouldn't be capital.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Nov 29, 2017, 01:13

added 30m of time spent at 2017-11-29

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Nov 29, 2017, 05:45

![image](/uploads/5ea38b5e1b12d60d78850c1dfadc5716/image.png)

@smasih How is that possible when Fairlawn has been uploading these files?  Thx, Tim

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 29, 2017, 08:12

Update from Cori:

FYI- we don't need to use a file at all for Webster City. We are only adding Staged fees. The Outbound sites also don't need to use a file to upload but have been given a blank one to use since SAB looks for that upload. Thanks Cori 

Response from Me:

The Webster City Billing Cycle is now at the Apply stage. Please continue the billing cycle appropriately. The support team has found there is an issue with the naming of the file uploaded, due to capitol letters. This however, should be resolved by the next billing cycle. 

Cori - The upload step is part of the universal billing cycle in SA Billing. Currently there is no way around this step other then to upload a blank file.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Nov 29, 2017, 08:14

@smasih 

As @tim.traylor pointed out that the Fairlawn site is uploading the exact same file using the same file naming convention without issue. We need to have this resolved by Webster City's next billing cycle.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Dec 7, 2017, 14:12

@smasih @pchaudhary @tim.traylor @kace.coady 

Any updates on this? All other sites are able to upload files with uppercase characters.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Dec 7, 2017, 23:50

It didn't do any change, but when tried to upload the file `Webster_City_empty_usage.txt` it worked.
Please check if it's working for you as well.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Dec 8, 2017, 08:07

@smasih 

Thank you, I have informed the site and will update accordingly.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Dec 22, 2017, 09:42

@smasih @tim.traylor 

Just received feedback from Jesus, that it will not upload a file with spaces in the name. Please resolve this.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Dec 25, 2017, 23:08

@tim.traylor  @kdjstudios  Is naming convention on usage files an issue..? 

I checked on old files, and was not able to find any with spaces in it's name.

If it's a necessity  for site/Jesus please send over the usage file to us we will se what we can do.

thanks

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Dec 26, 2017, 11:45

@smasih 

I believe we should allow for uploading of files regardless of what the name is, or contains. If it has unsupported symbols we should simply be filtering those out and replacing them with an appropriate symbol, like an underscore. I do not believe there should be any reason a file gets rejected due to its name. 

@tim.traylor @kace.coady 

What are you thoughts?

**Comment by kdjstudios** [comment]
In GitLab by @abakshi on Jan 4, 2018, 06:06

Require a discussion with @tim.traylor

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Jan 9, 2018, 09:26

Please add a regex replace that replaces 'invalid' characters with underscores.  That way they can name it whatever they want and we can still process it.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jan 10, 2018, 04:37

Removed the `Usage File name` limitation *(except special characters)* on merge and will release on production under current release cycle [+2018-01-20+].

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jan 10, 2018, 04:37

added 40m of time spent at 2018-01-10

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jan 20, 2018, 04:40

this was done on production

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jan 22, 2018, 09:56

Thanks. Marking for close.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Apr 11, 2018, 13:11

closed
