### ISSUE TITLE
"Ruby Upgrade" The Gemfile and Gemfile.lock on production are broken.

### ISSUE THREAD

**Issue by kdjstudios** [kdjstudios/SABillingGitlab#917]
In GitLab by @thomas.gentry on May 23, 2018, 11:26

I needed to rebundle the Gems on my local development environment.

To do this I removed all of my Gems and then copied the Gemfile and Gemfile.lock from production.

They do not build.

After manually installing every Gem and Gem version to match the versions on production I still get:

> Bundler could not find compatible versions for gem "devise":
>   In snapshot (Gemfile.lock):
>     devise (= 3.1.0)
> 
>   In Gemfile:
>     devise_invitable was resolved to 1.3.6, which depends on
>       devise (>= 2.1.2)
> 
>     devise_ldap_authenticatable was resolved to 0.7.1, which depends on
>       devise (~> 2.0)
> 

How are you building your environment? How is production even running at all?

I'm using the master branch of sabilling_merge.

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on May 24, 2018, 07:16

changed title from **The Gemfile and Gemfile.lock {-ON PRODUCTION-} are broken.** to **The Gemfile and Gemfile.lock {+on production+} are broken.**

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on May 24, 2018, 07:16

changed the description

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on May 24, 2018, 07:34

I need this ASAP so I can test and push my fix for the negative tax issue.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on May 24, 2018, 08:03

@smasih @pchaudhary @rchauhan @thomas.gentry @tim.traylor 

Updating the priority of the ticket. Please respond to Thomas's request. This is preventing Thomas from making progress.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on May 24, 2018, 08:56

@thomas.gentry @kdjstudios 

> How are you building your environment? How is production even running at all?

We are directly working on dev servers. 


Did you try running `bundle update devise` ..?

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on Jun 1, 2018, 07:55

Here are working Gemfile and Gemfile.lock files that successfully bundle with Ruby v2.5.0.

I think the Gemfile can be cleaned up a bit as there are quite a few Gems I doubt are used at all.

[Gemfile](/uploads/513bda848ab8634f66851c445eecb6bc/Gemfile)

[Gemfile.lock](/uploads/c7915b7e443c5100e3474aa1da891be6/Gemfile.lock)

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on May 24, 2018, 09:18

Yes.

Please provide me with: 

* the version of devise you currently have running
* the version of devise_invitable you currently have running
* the version of devise_ldap_authenticatable you currently have running

and then provide the working config/initializers/devise.rb

It's insane that we can't reliably rebuild our production environment.

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on May 24, 2018, 09:32

according to rvm on merge:

devise_ldap_authenticatable

isn't even installed...but:

```
[sabilling@merge sabilling]$ cat config/initializers/devise.rb | grep ldap
  # config.ldap_logger = true
 config.ldap_logger = true
  #### config.ldap_create_user = true
  config.ldap_create_user = true
  # config.ldap_update_password = true
  # config.ldap_config = "#{Rails.root}/config/ldap.yml"
  # config.ldap_check_group_membership = false
  # config.ldap_check_attributes = false
  config.ldap_use_admin_to_bind = Figaro.env.ldap_use_admin_to_bind
  # config.ldap_ad_group_check = false
```

Which makes the application fail when trying to start it:

```
λ tg [~/Projects/sabilling_merge] at  master -!?
→ rails s                                                                                                                                     [d15541d]
=> Booting Unicorn
=> Rails 3.2.12 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/home/tg/Projects/sabilling_merge/config/initializers/devise.rb:7:in `block in <top (required)>': undefined method `ldap_logger=' for Devise:Module (NoMethodError)
	from /home/tg/Projects/sabilling_merge/.gem/ruby/1.9.3/gems/devise-3.5.10/lib/devise.rb:282:in `setup'
	from /home/tg/Projects/sabilling_merge/config/initializers/devise.rb:3:in `<top (required)>
```

So I'll repeat. Does anyone know how this application is even running in it's current state?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on May 25, 2018, 05:51

@thomas.gentry @kdjstudios 

> - the version of devise you currently have running
>
> - the version of devise_invitable you currently have running
>
> - the version of devise_ldap_authenticatable you currently have running


As per the Gemfile.lock

* devise-2.2.4
* devise-3.1.0
* devise_invitable-1.3.6
* devise_ldap_authenticatable-0.7.1 

but this is what I got from gems directory in server

devise-2.2.4
devise-3.1.0
devise-3.4.1
devise_invitable-1.1.8
devise_invitable-1.3.6
devise_ldap_authenticatable-0.8.3

can you copy this gem [devise_ldap_authenticatable-0.8.3.zip](/uploads/d5447c658cac56eb385082482a9aff12/devise_ldap_authenticatable-0.8.3.zip) in your local system 


- config/initializers/devise.rb in the repo is being used by all the sab servers.

- lastly, you might need to whitelist your IP on ldap server (Tim should be the right person to talk about this)


Please,Let us know if it worked.

**Comment by kdjstudios** [comment]
In GitLab by @abakshi on May 25, 2018, 06:07

@thomas.gentry 

If this does not work, then we may do a shared join.me session or can ssh into your system if we can have credentials(Hoping that our Answernet VPN access should work in this case).

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Jun 8, 2018, 06:19

@smasih What I need now is an estimate for two different options:
1.  The time required to upgrade and test ONLY updating the minimum number of gems to upgrade the ruby.
1.  The time required to upgrade and test EVERY gem that can be upgraded along with the ruby upgrade.

Also, please let me know if there is a utility or some code analysis thing you can run against the app and determine what gems are not in use so we can remove them.

Thx

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jun 9, 2018, 05:14

removed milestone

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 11, 2018, 05:48

@tim.traylor 

> The time required to upgrade and test ONLY updating the minimum number of gems to upgrade the ruby.

It took me half day to upgrade `ruby 2.5.0` and successfully run bundle all the dependencies for SAB on my local machine. I am aware which issues might get in our way. (Gemfile.lock posted by @thomas.gentry was really helpful)
So just upgrading the ruby to 2.5.0 will take `3 hours`

There is no dependency mismatch so the system is not throwing errors right away. But we need to test each module of the app to ensure if it's working. (**Still in process of upgrading and running SAB on my local.**)


> The time required to upgrade and test EVERY gem that can be upgraded along with the ruby upgrade.

Due to ruby update, we need to upgrade other gems. (System automatically resolves dependency)


> Also, please let me know if there is a utility or some code analysis thing you can run against the app and determine what gems are not in use so we can remove them.

There is no command which can do it, we have to do it manually. [stackoverflow answer](https://stackoverflow.com/questions/19167563/how-to-find-unused-gems-and-cleanup-gemfile?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

`bundle clean --force` removes old gems .. but by doing this we cannot be certain that the gems it removed are not being used.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 12, 2018, 07:35

@tim.traylor 

tried out this on our local and we were able to get the sign in page, we were not able to proceed further due to ldap issue. (we cannot request ldap server from our local.)

So we need any dev server for the testing.

Please let us know should we proceed or is this something that will be done by Thomas.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 13, 2018, 01:55

@tim.traylor 

checked with our sysadmin, our ip is not whitelisted (maybe they were changed)

![Screenshot-7](/uploads/73b1c870a595b8e5d6abd878a3f86ec5/Screenshot-7.png)

**here are our ip which needs to be whitelisted.**  
`49.205.176.94`  
`122.160.22.126`

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 15, 2018, 05:18

#### on running `ldapsearch -x -h 104.37.108.254` on local

![Screenshot-7](/uploads/f44aa17350464cd3b177c33cc1d97a2d/Screenshot-7.png)

#### on running similar command on merge server

![Screenshot-8](/uploads/684cda3315caa2f5d8704729f12acb31/Screenshot-8.png)

hence we are not able to access ldap server locally.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 19, 2018, 07:55

@thomas.gentry @tim.traylor 

as per the discussion with Tim, instead of spending time on fixing LADP issue on local we should use staging server instead.

Our server is running on Rails 3.2.12 which is an older version of rails but ruby version we tend to use is the latest stable (`2.5.0`)... so due to which we had few dependency issues. 

here is the updated Gemfile and Gemfile.lock

[Gemfile.lock](/uploads/546a6ffbe90d5766f5ca6f771a63b73e/Gemfile.lock)

[Gemfile](/uploads/218717d7be857d46d73f67837c912150/Gemfile)


Staging server (staging.sabilling.com) is running on `ruby 2.5.0` and we did a very basic testing and it seems fine till now.

#### Estimate 4-5 hours for upgrading  
#### Testing (for testing we need a plan)

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Jun 19, 2018, 09:13

@smasih We can use our big test case plan from the merge, but I want to add to that any functionality that may be affected by the upgrade of the gems.  So we need to know what processing/functionality each of the upgraded gems handles so we know what else to add to the test.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 20, 2018, 05:21

Left is old Right is new

[gemfile_compare_old_vs_new.htm](/uploads/2371f48593811903ebd1f9446b3c4eaa/gemfile_compare_old_vs_new.htm)

The only alarming changes I would consider is 

` mongoid (>= 2.0.0) - to - mongoid (>= 3.0)`  Orm for Mongo, there are chances that query syntax might have changed for few things.

`devise` Tested working properly

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 21, 2018, 07:07

@tim.traylor @thomas.gentry 

**Working on the gem list as discussed by Tim.**

However, didn't find any mongoid issues, I was able to run most of the reports (which usually do have complex queries)

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Jun 22, 2018, 05:56

@smasih @thomas.gentry Reminder to you guys that we need to review the gems on Tuesday's meeting.  We need to understand how much additional re-testing is going to be required.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 25, 2018, 02:02

@tim.traylor 

Hi Tim,

Not sure what is required for the discussion or what homework we need to do ..?

here is a sample of old and new gem version with their functionality, let us know if this is some what like you are expecting.
[old_gemfile_vs_new_gemfile.csv](/uploads/38b08b1d6735876cfe4ee98a5a199bc2/old_gemfile_vs_new_gemfile.csv)

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jun 26, 2018, 08:33

@thomas.gentry @tim.traylor 

here is the updated file [old_gemfile_vs_new_gemfile.xls](/uploads/9b229bd3d308baf2579716081a08e958/old_gemfile_vs_new_gemfile.xls)

**Comment by kdjstudios** [comment]
In GitLab by @tim.traylor on Jun 26, 2018, 09:47

@smasih Sumeet, pls update tasks you know with the amount of test time needed.  When done, Thomas or Kyle can fill in anything else that's needed. [old_gemfile_vs_new_gemfile.xls](/uploads/e80046d3475c5a65da3871ad5955ed20/old_gemfile_vs_new_gemfile.xls)

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jun 27, 2018, 05:39

Hi [Thomas] (@thomas.gentry ), [Kyle] ( @kdjstudios ) & [Tim] (@tim.traylor ),   

We have updated the list as per your suggestion. [updated_old_gemfile_vs_new_gemfile.xlsx](/uploads/f1184dc1800714330ba4479aa7edc290/updated_old_gemfile_vs_new_gemfile.xlsx)

Merge testing: to & fro of testing sheets with Kyle took a whole week but in total it took like 15-16 hrs.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 6, 2018, 07:30

Hi [Thomas] (@thomas.gentry ), [Kyle] ( @kdjstudios ), [Tim] (@tim.traylor ) & [Atul] ( @abakshi ),   

We have found some bugs while testing the upgraded ruby on Staging server.   
1- Rails console is not working -  
```
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/browser-0.3.2/lib/browser/methods/language.rb:42: warning: key "gd" is duplicated and overwritten on line 80
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/builder-3.0.4/lib/builder/xchar.rb:111: warning: constant ::Fixnum is deprecated
**************************************************
⛔️ WARNING: Sidekiq server is no longer supported by Rails 3.2 - please ensure your server/workers are updated
**************************************************
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/roxml-3.3.1/lib/roxml/definition.rb:156: warning: constant ::Fixnum is deprecated
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/authorizenet-1.8.9.1/lib/authorize_net/api/schema.rb:2400: warning: constant ::Fixnum is deprecated
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/authorizenet-1.8.9.1/lib/authorize_net/api/schema.rb:2417: warning: constant ::Fixnum is deprecated
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/authorizenet-1.8.9.1/lib/authorize_net/api/schema.rb:2419: warning: constant ::Fixnum is deprecated
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} (0.8593ms)
Traceback (most recent call last):
        20: from script/rails:6:in `<main>'
        19: from script/rails:6:in `require'
        18: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
        17: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
        16: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/commands/console.rb:27:in `start'
        15: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/application.rb:152:in `load_console'
        14: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/application.rb:304:in `initialize_console'
        13: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
        12: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
        11: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
        10: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
         9: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/railties-3.2.12/lib/rails/console/app.rb:2:in `<top (required)>'
         8: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
         7: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
         6: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
         5: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
         4: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/test_case.rb:1:in `<top (required)>'
         3: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
         2: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
         1: from /home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/home/sabilling/.rvm/gems/ruby-2.5.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/testcase (LoadError)
```
2- Sidekiq server is no longer supported by Rails 3.2.  
* We have to resolve the 1^st error to work on this.

I am working on the resolution of first error.

Rough Estimate - 8 Hour.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @thomas.gentry on Jul 6, 2018, 09:21

Please add

```
gem 'test-unit'
```

to the Gemfile and bundle to fix this problem.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 11, 2018, 07:33

Hi [Kyle] ( @kdjstudios ) & [Thomas] ( @thomas.gentry ),  

We have successfully added the gem 'test-unit' and bundled it. Now, the rails console is working but the Sidekiq Warning is still there.  
```
Sidekiq server is no longer supported by Rails 3.2 - please ensure your server/workers are updated
```

We are still working on this to resolve.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 16, 2018, 02:23

changed title from **The Gemfile and Gemfile.lock on production are broken.** to **{+**"Ruby Upgrade"** +}The Gemfile and Gemfile.lock on production are broken.**

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 16, 2018, 02:24

changed title from **{-**"Ruby Upgrade"**-} The Gemfile and Gemfile.lock on production are broken.** to **{+"Ruby Upgrade"+} The Gemfile and Gemfile.lock on production are broken.**

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 18, 2018, 05:05

Hi [Kyle] ( @kdjstudios ),   

We have found some functionalities which are the add-on after the Merge release, so as per our last call discussion, please add those also in your testing checklist.  

1.  New Account Ledger - with site conversion dates and pending fees.  
1.  Download Receipt functionality of Credit Card transactions, E-Check transactions.  
1.  Download Szeto Mapping PDF.
1.  Invoice Tracking on Manual Invoice edit (*created by, last edited by*)
1.  Check if an inactive account is eligible to create an invoice.
1.  Rate plan per account report.
1.  Added the modified Invoice, Service date functionality on Billing cycle index page.
1.  Added the functionality of Run Blank Usage on Billing cycle index page. 
1.  Only the Site level active activities/recurring fees should come up under the selection box in the accounts.  
1.  Notification of Staged fee  - The notice on the staged fees page that on which billing cycle those fees are going to apply.
1.  The creation of an invoice is not allowed when the current billing cycle is finalized.
1.  The functionality of Site Billing cycles on the Billing Cycle index page.
1.  The pop-up functionality on the terminated accounts while making payments.
1.  SAB News functionality.
1.  Disable local forms for LDAP users.

Please note that these all changes are marked by us by looking on the commit differences of Current code and at the time of Merge release.  

We also would like to confirm that the testing server is **[Staging] (www.staging.sabilling.com)**

Hope this helps.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 18, 2018, 08:35

@pchaudhary 

Thank you. I will start updating the test case spreadsheet accordingly. 

Is this ready for testing?

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 19, 2018, 24:33

@kdjstudios 

Yes, it is ready that's what we discussed on our tuesday call.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 19, 2018, 08:22

@smasih Thanks. Lets please mark these tickets accordingly then in the correct swim lanes so we are tracking them successfully. :-)

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 19, 2018, 11:36

@smasih @pchaudhary @tim.traylor 

Testing:

1. Navigated to "https://staging.sabilling.com/users/sign_in"
2. Typed in username and password. Clicked sign in.
3. Received error. 

![image](/uploads/cc7562072c1f8d5ea53cd873fe70a693/image.png)

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 19, 2018, 11:46

@tim.traylor 

I know we mentioned having me do all of the testing, but I think after the first error being reported above we may want to have the Aavaz team do a few of the basic testing first, as to insure I am even able to even test. Below I have listed a few of the basic test cases, These should not take more then 30 minutes to test total. 

Test items for Aavaz?

1. Login (AD and Local) - 5 minutes
2. Create customer and account - 10 minutes
 - Simply create blank accounts with only required fields. No need to add activities, fees, etc as that I will test those.
3. Complete billing cycle with usage - 10 minutes.
 - Simply run through the billing, no need to check numbers, revert, send fax, email, etc as that I will test those. Basically insure we are able to upload, apply, and finalize.
4. Complete billing cycle without usage - 5 minutes.

I would hope that if Aavaz is able to test those Items, That should allow me access to be able to successfully test all most other test cases, as long as those are working.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 20, 2018, 08:51

@kdjstudios 

It was working before when we checked, but after updating it with new production code it stopped working. Sorry for the delay.

* Login is working  
* Billing cycle (on demo site) working with and without usage   
* we were able to create new customer  
* we are able to view any existing accounts.   
* ERROR: not able to update and create new account  ( `error not resolved still working on it` )
 * Error is coming from a gem "Exception Notifier" which is being used globally so there are chances that some of the stuff will not work. Please let us fix this first before you spend your time on testing ruby upgrade.

thanks

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 20, 2018, 11:53

@smasih @tim.traylor 

Thank you, please let us know when to test.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 23, 2018, 08:32

@thomas.gentry @tim.traylor 

Hi @kdjstudios 

we have fixed the errors.. and its ready for your testing.

I have done the basic testing before forwarding it to you.

Lastly, **please test it on MERGE.sabilling.com** instead of staging.

thanks

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 23, 2018, 10:50

@smasih 

Thank you for the update. I will start testing and post the test case spreadsheet with my results once finished.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 23, 2018, 15:44

@smasih @pchaudhary @tim.traylor 

I must say overall testing went rather smooth! A few issues found that are highlighted and have red text. There are also a few concerns which are just highlighted. A few items I did not get to test in the first pass are labeled "Untested" and should have a note why I did not test them yet.  

[Ruby_Test_Case_Merge_7-23-18.xlsx](/uploads/9f3d44b8d1cd8d8d912f457569f20cf5/Ruby_Test_Case_Merge_7-23-18.xlsx)

NOTE: I received about 40 error emails sent during the time it took me to test everything. (2:45pm mdt to 3:45pm mdt)

Screenshots for a few of the issues found. 

Late Charge Layout issue: ![image](/uploads/5f1bc1377101d5dbd2af7fe1fcd253c9/image.png)

Taxes and Holiday fees invalid input issue:  ![image](/uploads/e959e1bb70b908ea0e663521531f675c/image.png)

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 24, 2018, 07:32

Hi [Kyle] ( @kdjstudios ),   

Thanks for the testing.  

We have gone through the report sent by you & most of the failed tests are because of the older branch in Merge, however, we have fixed those by updating the branch with the current production branch.   
There is still one issue pending of the "**Prawn**"  gem which is used as the pdf generator for the SAB, so wherever the process goes through the pdf generation, then the issue occurs.   
The upgraded ruby does have the compatibility issue with that Gem, so we have to fix that by researching with their documentation.  

[Ruby_Test_Case_Merge_7-23-18.xlsx](/uploads/9e4069da491bbe7a4f72861b9697b8bb/Ruby_Test_Case_Merge_7-23-18.xlsx)

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 24, 2018, 08:28

@pchaudhary @tim.traylor 

Thank you for the update. I was hoping that most of those issues were due to not being updated too. Glad to hear that! Please let me know once the PDF issues is resolved and then I will retest everything.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 25, 2018, 05:23

Hi [Kyle] ( @kdjstudios ),   

We have successfully fixed the Prawn pdf gem issue. Now you can go for the further testing. 

Please check the updated Test cases.  

[Ruby_Test_Case_Merge_7-23-18.xlsx](/uploads/dbdda0747c23d38b2276584b43e8e575/Ruby_Test_Case_Merge_7-23-18.xlsx)

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @smasih on Jul 26, 2018, 04:38

@kdjstudios 

Can you please test this today, so that we can release this on upcoming Saturday?

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 30, 2018, 15:46

@smasih @pchaudhary 

Thank you for the update. However, I am unable to log into MERGE. please fix this and let me know when ready to test. 

![image](/uploads/388821b8fa6ca4543cb0b98bb4d75beb/image.png)

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Jul 31, 2018, 07:31

Hi [Kyle] ( @kdjstudios ),  

Sorry for the inconvenience, we had switched the branch yesterday for our development purpose & forgot to put it back to the testing one.   

Please check today.  

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Jul 31, 2018, 11:28

@pchaudhary 

Thank you for the updates. spreadsheet updated: [Ruby_Test_Case_Merge_7-31-18.xlsx](/uploads/9334fce79c3ceba905e230b104024601/Ruby_Test_Case_Merge_7-31-18.xlsx)

## Screenshots below:

**Activities errors:**
![image](/uploads/a89c90121690d95c70f52159d6057c2b/image.png)

**Resource ID duplciate Errors:**
![image](/uploads/0992704e59b3f0d770d1a24267c3e404/image.png)

**Tried to delete current cycle to bring back "send email and send fax" buttons on cycle.**
![image](/uploads/7ee1cdf8eee5c458b2df71c2694c397d/image.png)

**Invoices By Site - Send email notification**
![image](/uploads/0d0cb15fbc9e8a0a94231c74517a6c17/image.png)

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Aug 1, 2018, 05:00

Hi [Kyle] (@kdjstudios ),   

Thanks for the updates. Please find the updated spreadsheet of the Ruby Upgrade Test: 
 [Aavaz_Ruby_Test_Case_Merge_7-31-18.xlsx](/uploads/dff709191a4b279752ac8216870b8d83/Aavaz_Ruby_Test_Case_Merge_7-31-18.xlsx)


*  Most of the failed points are due to the different issues & they have nothing to do with the Ruby Upgrade. Albeit, we have already the tickets regarding those issues (#892 and #966 ) & they are going to be released on our upcoming milestone.  
*  If the billing cycle accounts are marked for email/fax invoices and does not have email/fax address on them, then the notification comes up with the error lines. 
  ![image](/uploads/f1c3960ed34c04fff90d0ab0bc3a0f54/image.png)


Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Aug 1, 2018, 05:00

assigned to @pchaudhary

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Aug 3, 2018, 09:05

@pchaudhary @abakshi @smasih @tim.traylor 

Updated spreadsheet. [Ruby_Test_Case_Merge_08-03-18.xlsx](/uploads/4c581cf6d60ca07a632ddaf40b4e8e6e/Ruby_Test_Case_Merge_08-03-18.xlsx) There should be a ticket now for all items that were not marked as pass. But as pointed out by @pchaudhary these are not related to this ticket. So marking for ready per @pchaudhary comments.

**Comment by kdjstudios** [comment]
In GitLab by @pchaudhary on Aug 4, 2018, 06:16

Hi [Kyle] ( @kdjstudios ) & [Tim] ( @tim.traylor ),   

Hurray, :smiley: 

We have **successfully upgraded the Ruby 2.5.0 on both of the Production servers**. We have also done the basic testing (eg: Account/Site/Customer - edit/create, Billing, Report, Invoice).

Here is the Updated [Aavaz_Ruby_Test_Case_Merge_08-04-18.xlsx](/uploads/c3636df91be6edc25a55bc0a88ecfba7/Aavaz_Ruby_Test_Case_Merge_08-04-18.xlsx) Test case list.

Thanks.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Aug 4, 2018, 12:19

@pchaudhary @smasih @tim.traylor

I did some quick double checking of the testing Aavaz did in regards to the Ruby upgrade before leaving town today. Everything looks good for the Ruby aspect.  

@tim.traylor 

Please see the other tickets that were marked ready but did not appear to be released this week when they should have been. Please discuss with the Aavaz team when they will be released. 


Everyone, have a great next week. Just a reminder I am out of town until the 12th and will not have any source for communication until them.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Aug 16, 2018, 11:46

Marking for close, as this was released and I believe all bugs were resolved now.

**Comment by kdjstudios** [comment]
In GitLab by @kdjstudios on Aug 16, 2018, 12:01

closed
